clear legacy code

diff --git a/ayer-release b/ayer-release
--- a/ayer-release
+++ b/ayer-release
@@ -1,8 +1,10 @@
 #!/bin/bash
 
-. /usr/lib/ayer/functions.sh
-
 # arguments: version_name
+
+source /usr/lib/ayer/functions.sh
+
+load_config
 
 function create_and_publish_tag() {
     local git_project_dir="$1"
@@ -10,24 +12,29 @@ function create_and_publish_tag() {
     cd "${git_project_dir}"
     git tag --force "$version_name" "$trunk_name"
     git push --tags origin
-}    
+}
 
 version_name="${1%_trunk}"
 trunk_name="${version_name}_trunk"
 
-# TODO: check for validity trunk_name
+# TODO: check trunk_name for validity
 # TODO: manipulate version tree data
 
-[ -d "$YUM_REPO_DIR/$trunk_name" ] || die "trunk directory $YUM_REPO_DIR/$trunk_name does not exist"
-[ ! -d "$YUM_REPO_DIR/$version_name" ] || die "release directory $YUM_REPO_DIR/$version_name already exists"
+build_commit="origin/$trunk_name"
+target_path="$version_name"
+previous_ref=""
+build_release="$trunk_name"
+
+[ ! -d "$YUM_REPO_DIR/$target_path" ] || die "error: release directory \`$YUM_REPO_DIR/$target_path' already exists"
+
+ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_release"
 
 git_repos_dir="${BASE_WORKDIR}/git"
-
 mkdir -p "$git_repos_dir"
-
 cd "$git_repos_dir"
-create_and_publish_tag release.git
+create_and_publish_tag ${BASE_PROJECT}.git
 
+cd "$git_repos_dir/${BASE_PROJECT}.git"
 git ls-tree -r "$trunk_name" | while read mode type hash path; do
     if [ "$mode" == 160000 ]; then
         cd "$git_repos_dir"
@@ -35,18 +42,4 @@ git ls-tree -r "$trunk_name" | while read mode type hash path; do
     fi
 done
 
-base_target_dir="$YUM_REPO_DIR/$trunk_name/$build_os"
-build_dir="$base_target_dir/build"
-mkdir -p "$build_dir"
-cd "$build_dir"
-rm -rf *RPMS *LOGS
-
-build_release_srpm "$trunk_name" --release "$version_name"
-cd "$build_dir"
-build_final_rpms
-
-rpms_dir="$build_dir/RPMS"
-mv "$rpms_dir/"*-release-*rpm "$base_target_dir"
-rm -rf "$build_dir"
-
-mv "$YUM_REPO_DIR/"{$trunk_name,$version_name}
+replace_repos "$YUM_REPO_DIR/$target_path"
