2012-10-11

diff --git a/ayer-accept b/ayer-accept
--- a/ayer-accept
+++ b/ayer-accept
@@ -1,88 +1,112 @@
 #!/bin/bash
 
-. /etc/ayer/functions.sh
-
+. /usr/lib/ayer/functions.sh
+git_repos_dir="${BASE_WORKDIR}/git"
 
 PROG=$(basename "$0")
 
-TEMP=`getopt -n $PROG  -o t:,b:,o:,u: -l topic:,branch:,owner:,user:,os: -- "$@"` || exit 1
+TEMP=`getopt -n $PROG  -o c: -l commit: -- "$@"` || exit 1
 eval set -- "$TEMP"
 
-ayer_os=centos6
 
 while [ "$#" -gt 0 ]; do
     case "$1" in
-        -t|--topic)
-            ayer_topic=$2
-            shift
-            ;;
-        -b|--branch)
-            ayer_branch=$2
-            shift
-            ;;
-        -o|--owner)
-            ayer_owner=$2
-            shift
-            ;;
-        -u|--user)
-            ayer_user=$2
-            shift
-            ;;
-        --os)
-            ayer_os=$2
+        -c|--commit)
+            build_commit=$2
             shift
             ;;
     esac
     shift
 done
+[ -n "$build_commit" ] || die "build commit is unknown"
 
-base_target_dir="$YUM_REPO_DIR/dev/$ayer_user/$ayer_branch/$ayer_topic/$ayer_os"
-target_yum_repo_dir="$base_target_dir/main"
 
-git_dir="$BASE_WORKDIR/"
-mkdir -p "$git_dir"
-cd "$git_dir"
+#########
+# FIXME: this code is too long...
+commit_info_file=$(mktemp /tmp/ayer.build.XXXXXX)
+gerrit_command query "project:release commit:$build_commit" --current-patch-set > $commit_info_file
+while read key value; do
+    case "$key" in
+        branch:)
+            build_branch=$value
+            ;;
+        ref:)
+            release_refspec=$value
+    esac
+done < "$commit_info_file"
+rm "$commit_info_file"
+[ -n "$build_branch" ] || die "build branch is unknown"
+#########
 
-ayer-gitlist -s "$GERRIT_SSH" -p "$GERRIT_PORT" "status:open owner:$ayer_owner branch:$ayer_branch topic:$ayer_topic $GERRIT_SUBMITTABLE"
-mkdir -p accept
-sort -u git.list > accept/submittable
-ayer-gitlist -s "$GERRIT_SSH" -p "$GERRIT_PORT" "status:open owner:$ayer_owner branch:$ayer_branch topic:$ayer_topic"
-sort -u git.list > accept/all
-diff accept/all accept/submittable > accept/diff
+git_dir="$BASE_WORKDIR/git"
 
-if [ -s accept/diff ]; then
-    grep '^<' accept/diff | sed 's/^< /    /' > accept/unsubmittable
-    grep '^>' accept/diff | sed 's/^> /    /' > accept/extras
-    echo "cannot accept branch:$ayer_branch topic:$ayer_topic owner:$ayer_owner"
-    if [ -s accept/unsubmittable ]; then
-        echo "these changes cannot be submitted (low Code Review or Verify)"
-        cat accept/unsubmittable
-    fi
-    if [ -s accept/extras ]; then
-        echo "these changes can be submitted and override the latest changes"
-        cat accept/extras
-    fi
-    exit 2
-fi
+target_path="$build_branch/$build_os"
+base_target_dir="$YUM_REPO_DIR/$target_path"
+main_repo_dir="$base_target_dir/main"
 
-ayer-build-git "$git_dir" "$base_target_dir/build" "${ayer_branch%%_*}"
+[ -d "$main_repo_dir" ] || die "looks like there is no trunk: $main_repo_dir directory is missing"
 
-git_repos_list="${git_dir}/git.list"
-git_repos_dir="${git_dir}/git"
+release_git_dir="$git_dir/release.git"
+git_fetch_refspec "$release_git_dir" "$(gerrit_repo_ssh release)" "$release_refspec" &>/dev/null
+cd "$release_git_dir"
+
+git fetch origin "$build_branch:refs/heads/$build_branch" &>/dev/null
+query_list=$(git diff-tree -r $build_branch..$build_commit |
+    while read mode1 mode2 hash1 hash2 ignored; do
+        if [ "$mode2" == 160000 ]; then
+            echo "commit:$hash2 OR"
+        fi
+    done
+)
+query_list=${query_list% OR}
+
+build_dir="$base_target_dir/build"
+mkdir -p "$build_dir"
+cd "$build_dir"
+rm -rf *RPMS *LOGS
+git_list="$build_dir/git.list"
+
+rm -f "$git_list"
+gerrit_command query "$query_list" --current-patch-set | while read key value; do
+    case "$key" in
+        project:)
+            project=$value
+            ;;
+        ref:)
+            echo "$value $project" >> $git_list
+            ;;
+    esac
+done
+
+build_srpms "$git_dir" "${build_branch%%_*}"
+
+cd "$build_dir"
+build_final_rpms
 
 cd "$git_repos_dir"
+
+echo "$release_refspec release" >> "$git_list"
+
 while read treeish repo_name; do
     repo_name="${repo_name%.git}"
     cd "$git_repos_dir/${repo_name}.git"
-    git fetch -p origin
-    ssh -p "$GERRIT_PORT" "$GERRIT_SSH" gerrit review --project "$repo_name" --message "'Accepted to trunk'" --submit $(git rev-list origin/$ayer_branch..HEAD)
-done < "$git_repos_list"
+    git fetch origin "$build_branch:refs/remotes/origin/$build_branch" "$treeish:refs/remotes/origin/$treeish"
+    difference=$(git rev-list origin/$build_branch..origin/$treeish)
+    if [ -n "$difference" ]; then
+        ssh -p "$GERRIT_PORT" "$GERRIT_SSH" gerrit review --project "$repo_name" --message "'Accepted to trunk'" --submit $difference &>/dev/null
+        git fetch origin "$build_branch:refs/remotes/origin/$build_branch"
+        difference=$(git cherry -v origin/$build_branch origin/$treeish)
+        if [ -n "$difference" ]; then
+            die "not all commits can be accepted to $repo_name:
+$difference"
+        fi
+    fi
+done < "$git_list"
 
-ready_rpm_dir="$base_target_dir/build/RPMS/"
-base_target_dir="$YUM_REPO_DIR/$ayer_branch/$ayer_os"
+ready_rpm_dir="$build_dir/RPMS/"
 target_yum_repo_dir="$base_target_dir/main"
 mkdir -p "$target_yum_repo_dir"
 mv "$ready_rpm_dir/"*.rpm "$target_yum_repo_dir"
-ayer-cleanrepo "$target_yum_repo_dir"
+ayer-clean-repo "$target_yum_repo_dir"
 createrepo "$target_yum_repo_dir"
-
+rm -rf "$build_dir"
