2012.10.19

diff --git a/ayer-accept b/ayer-accept
--- a/ayer-accept
+++ b/ayer-accept
@@ -38,33 +38,28 @@ rm "$commit_info_file"
 [ -n "$build_branch" ] || die "build branch is unknown"
 #########
 
-git_dir="$BASE_WORKDIR/git"
+trunk_name=$build_branch
+target_path="dev/$trunk_name"
+previous_ref="$trunk_name"
+build_release="$trunk_name"
 
-target_path="$build_branch/$build_os"
 base_target_dir="$YUM_REPO_DIR/$target_path"
-main_repo_dir="$base_target_dir/main"
 
-[ -d "$main_repo_dir" ] || die "looks like there is no trunk: $main_repo_dir directory is missing"
-
-target_path="$build_branch"
-previous_ref="$build_branch"
+[ -d "$base_target_dir" ] || die "looks like there is no trunk: $base_target_dir directory is missing"
 
 ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_branch"
 
-
-cd "$git_repos_dir"
-
-echo "$release_refspec release" >> "$git_list"
+build_dir="$base_target_dir/build"
+git_list="$build_dir/git-diff.list"
 
 while read treeish repo_name; do
     repo_name="${repo_name%.git}"
-    cd "$git_repos_dir/${repo_name}.git"
-    git fetch origin "$build_branch:refs/remotes/origin/$build_branch" "$treeish:refs/remotes/origin/$treeish"
-    difference=$(git rev-list origin/$build_branch..origin/$treeish)
+    cd "$git_dir/${repo_name}.git"
+    difference=$(git rev-list origin/$build_branch..$treeish)
     if [ -n "$difference" ]; then
         ssh -p "$GERRIT_PORT" "$GERRIT_SSH" gerrit review --project "$repo_name" --message "'Accepted to trunk'" --submit $difference &>/dev/null
         git fetch origin "$build_branch:refs/remotes/origin/$build_branch"
-        difference=$(git cherry -v origin/$build_branch origin/$treeish)
+        difference=$(git cherry -v origin/$build_branch $treeish)
         if [ -n "$difference" ]; then
             die "not all commits can be accepted to $repo_name:
 $difference"
@@ -72,10 +67,4 @@ $difference"
     fi
 done < "$git_list"
 
-ready_rpm_dir="$build_dir/RPMS/"
-target_yum_repo_dir="$base_target_dir/main"
-mkdir -p "$target_yum_repo_dir"
-mv "$ready_rpm_dir/"*.rpm "$target_yum_repo_dir"
-ayer-clean-repo "$target_yum_repo_dir"
-createrepo "$target_yum_repo_dir"
-rm -rf "$build_dir"
+replace_repos "$YUM_REPO_DIR/$target_path"
