make all scripts work
Change-Id: I13e424dea7d4157e602c42a3b52b5d0f0f57cd65

diff --git a/ayer-accept b/ayer-accept
--- a/ayer-accept
+++ b/ayer-accept
@@ -4,29 +4,13 @@ source /usr/lib/ayer/functions.sh
 
 load_config
 
-PROG=$(basename "$0")
+build_commit=$1
+build_branch=$2
 
-TEMP=`getopt -n $PROG  -o c:,b: -l commit:,branch: -- "$@"` || exit 1
-eval set -- "$TEMP"
+[ -n "$build_commit" -a -n "$build_branch" ] || die "usage: $(basename $0) build_commit build_branch"
 
-while [ "$#" -gt 0 ]; do
-    case "$1" in
-        -c|--commit)
-            build_commit=$2
-            shift
-            ;;
-        -b|--branch)
-            build_branch=$2
-            shift
-            ;;
-    esac
-    shift
-done
-[ -n "$build_commit" ] || die "build commit is unknown"
-[ -n "$build_branch" ] || die "build branch is unknown"
-
-
-commits_to_submit=$(ayer-is-acceptable -c "$build_commit" -b "$build_branch") || die "build commit cannot be accepted to trunk"
+echo "checking whether build commit can be accepted to trunk"
+commits_to_submit=$(ayer-is-acceptable "$build_commit" "$build_branch") || die "build commit cannot be accepted to trunk"
 
 
 trunk_name=$build_branch
@@ -41,7 +25,7 @@ base_target_dir="$YUM_REPO_DIR/$target_path"
 ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_branch"
 
 if [ -n "$commits_to_submit" ]; then
-    gerrit_command review --message "'Accepted to trunk'" --submit $commits_to_submit &>/dev/null
+    gerrit_command review --message "'Accepted to trunk'" --submit $commits_to_submit >/dev/null
 fi
 
 replace_repos "$YUM_REPO_DIR/$target_path"
diff --git a/ayer-release b/ayer-release
--- a/ayer-release
+++ b/ayer-release
@@ -7,14 +7,14 @@ source /usr/lib/ayer/functions.sh
 load_config
 
 function create_and_publish_tag() {
-    local git_project_dir="$1"
-    git_fetch_refspec "${git_project_dir}" "$(gerrit_repo_ssh "$git_project_dir")" "$trunk_name:refs/heads/$trunk_name"
-    cd "${git_project_dir}"
-    git tag --force "$version_name" "$trunk_name"
-    git push --tags origin
+    local project_name="$1"
+    cd "${git_dir}/${project_name}.git"
+    git tag --force "$version_name" "origin/$trunk_name"
+    git push origin "+$version_name"
 }
 
 version_name="${1%_trunk}"
+[ -n "$version_name" ] || die "usage: $(basename $0) version_name"
 trunk_name="${version_name}_trunk"
 
 # TODO: check trunk_name for validity
@@ -25,20 +25,17 @@ target_path="$version_name"
 previous_ref=""
 build_release="$trunk_name"
 
-[ ! -d "$YUM_REPO_DIR/$target_path" ] || die "error: release directory \`$YUM_REPO_DIR/$target_path' already exists"
+repodata_dir=$YUM_REPO_DIR/$target_path/$build_os/repodata
+[ ! -d "$repodata_dir" ] || die "error: looks like $version_name is released: directory \`$repodata_dir' already exists"
 
 ayer-build-function "$build_commit" "$previous_ref" "$target_path" "$build_release"
 
-git_repos_dir="${BASE_WORKDIR}/git"
-mkdir -p "$git_repos_dir"
-cd "$git_repos_dir"
-create_and_publish_tag ${BASE_PROJECT}.git
+create_and_publish_tag ${BASE_PROJECT}
 
-cd "$git_repos_dir/${BASE_PROJECT}.git"
-git ls-tree -r "$trunk_name" | while read mode type hash path; do
+cd "$git_dir/${BASE_PROJECT}.git"
+git ls-tree -r "origin/$trunk_name" | while read mode type hash path; do
     if [ "$mode" == 160000 ]; then
-        cd "$git_repos_dir"
-        create_and_publish_tag "$(basename "$path").git"
+        create_and_publish_tag "$(basename "$path")"
     fi
 done
 
diff --git a/hoy-feature b/hoy-feature
--- a/hoy-feature
+++ b/hoy-feature
@@ -27,6 +27,11 @@ if git rev-parse "$target_feature" &>/dev/null; then
 fi
 
 git fetch origin --recurse-submodules --tags
+
+if ! git rev-parse "origin/$target_branch" &>/dev/null; then
+    die "trunk \`$target_branch' is not found"
+fi
+
 git checkout -t -B "$target_feature" "origin/$target_branch"
 git submodule init
 git submodule update
